artifacts_root: artifacts
# Save the artifcats for all config

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/hritzs/data/raw/main/winequality-data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/winequality-red.csv
  STATUS_FILE: artifacts/data_validation/status.txt